services:
  db:
    build:
      dockerfile: ./Dockerfile.db
    restart: always
    ports:
      - 5432:5432
    container_name: db
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  app:
    build:
      dockerfile: ./Dockerfile.dev
    restart: unless-stopped
    ports:
      - 3001:3001
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
