FROM node:20.18.1-bullseye
RUN mkdir -p /app/node_modules && chown -R node:node /app
WORKDIR /app
COPY --chown=node:node package*.json .
USER node
RUN npm install
COPY --chown=node:node ./src .
EXPOSE 3001
CMD ["npm", "run", "prod"]