services:
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    container_name: db
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/postgresql/data

  app:
    build:
      context: .
      target: production
    restart: unless-stopped
    ports:
      - 3001:3001
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
