openapi: '3.0.2'
info:
  title: Customer subscriptions API
  version: '1.0'
servers:
  - url: http://localhost:3001
    description: Local server
paths:
  /customer:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customers'
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
    put:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
  /customer/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customers'
    delete:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No Content

  /subscription:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscriptions'
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Subscription'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
  /subscription/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
    delete:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No Content

  /customer-subscription:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerSubscriptions'
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerSubscriptions'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerSubscription'
    put:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerSubscriptions'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerSubscription'
  /customer-subscription/{customerId}:
    get:
      parameters:
        - name: customeriId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerSubscription'
    delete:
      parameters:
        - name: customerId
          in: query
          required: true
          schema:
            type: string
        - name: subscriptionId
          in: query
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No Content
  /custtomer-subscription/check-validity:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  valid:
                    type: boolean
                required:
                  - valid

components:
  schemas:
    Customers:
      type: array
      items:
        type: object
        $ref: '#/components/schemas/Customer'
    Customer:
      type: object
      properties:
        id:
          type: string
        lastname:
          type: string
        firstname:
          type: string
        email:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
      additionalProperties: false
      required:
        - id
        - lastname
        - firstname
        - email
        - createdAt
        - updatedAt

    Subscriptions:
      type: array
      items:
        type: object
        $ref: '#/components/schemas/Subscription'
    Subscription:
      type: object
      properties:
        id:
          type: string
        startDate:
          type: string
        endDate:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
      additionalProperties: false
      required:
        - id
        - startDate
        - endDate
        - createdAt
        - updatedAt

    CustomerSubscriptions:
      type: array
      items:
        type: object
        $ref: '#/components/schemas/CustomerSubscription'
    CustomerSubscription:
      type: object
      properties:
        paymentDate:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        subscription:
          type: object
          $ref: '#/components/schemas/Subscription'
        customerId:
          type: string
      additionalProperties: false
      required:
        - paymentDate
        - createdAt
        - updatedAt
        - subscriptionId
        - customerId
