### GETALL
GET http://localhost:3001/customer-subscription
content-type: application/json


### GET BY CUSTOMER ID
GET http://localhost:3001/customer-subscription/customer/2c05fdda-f466-4f5d-b773-7d836ac542d4
content-type: application/json


### ADD CUSTOMER SUBSCRIPTION
POST http://localhost:3001/customer-subscription
content-type: application/json

{
    "customerId": "331edea8-e003-4264-84c1-f023d561c7a4",
    "startDate": "2025-01-01",
    "endDate": "2025-03-31"
}


### UPDATE CUSTOMER SUBSCRIPTION (PAY)
PUT http://localhost:3001/customer-subscription
content-type: application/json

{
    "customerId": "2c05fdda-f466-4f5d-b773-7d836ac542d4",
    "subscriptionId" : "47db625a-0c8b-4775-8a19-1acca66f32f7",
    "paymentDate": "2024-11-01",
    "amount": 33
}

### DELETE CUSTOMER SUBSCRIPTION
DELETE http://localhost:3001/customer-subscription/?customerId=2c05fdda-f466-4f5d-b773-7d836ac542d4&subscriptionId=88187431-3e87-4431-a9f2-616bcdb6360a
content-type: application/json


### CHECK CUSTOMER SUBSCRIPTION VALIDITY AND NOTIFY
GET http://localhost:3001/customer-subscription/check-validity
content-type: application/json
